#!/bin/bash

# unpack
cd /tmp && \
unzip onload-package.zip && \
tar -zxf onload*.tgz && \
rm onload*.tgz && \
mv onload* onload_src 

# Build onload
cd /tmp/onload_src/scripts && \
./onload_build

#Make the archive name
KERNEL_VERSION=`uname -r`
ONLOAD_VERSION=`grep "version: onload" /tmp/onload_src/README | awk '{print $2}'`
ARCHIVE_NAME=openonload-${ONLOAD_VERSION}-kmod-${KERNEL_VERSION}

#Tar and compress
cd /tmp/onload_src && \
tar -cvzf /mnt/${ARCHIVE_NAME}.tgz *

echo "/tmp/${ARCHIVE_NAME}.tgz is now available on the host, you can exit this container"
